services:
   auth.provider.cas:
      class: getekid\cas\auth\provider\cas
      arguments:
          - @dbal.conn
          - @config
          - @user
      tags:
          - { name: auth.provider }